parameters:
  - name: name
    type: string
    default: ''

  - name: steps
    type: stepList
    default: []

  - name: images
    type: object
    default: [windows, ubuntu, macos]

  - name: pythonVersions
    type: object
    default: ['3.6', '3.7', '3.8']

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: $(os)
    strategy:
      matrix:
        ${{ each pythonVersion in parameters.pythonVersions }}:
          ${{ each image in parameters.images }}:
            ${{ format('{0} {1}', pythonVersion, image) }}:
              python_version: ${{ pythonVersion }}
              os: ${{ image }}-latest
              platform: ${{ image }}

    steps:
      - powershell: git config --global core.autocrlf false
        displayName: $(System.JobName) git config core.autocrlf

      - checkout: self

      - template: python/install-poetry-project.yaml@trim21
        parameters:
          python_version: $(python_version)

      - ${{ each s in parameters.steps }}:
          - ${{ s }}
