pull_request_rules:
  - name: label conflicts
    conditions:
      - conflict
    actions:
      label:
        toggle:
          - conflict

  - name: Automatic merge on approval
    conditions:
      - or:
          - "#approved-reviews-by>=1"
          - label=auto-merge
      - "created-at<=24h ago"
      - base=master
      - -check-success=dist-files
      - -check-success=mypy
      - -check-success=pre-commit
      - -check-success=downloader
      - -check-success=test
    actions:
      merge:
        method: squash
