[mypy]
disallow_untyped_defs = true
;disallow_untyped_defs = false
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
show_error_codes = true
;allow_return_value = false
;ignore = return_value
pretty = true

[mypy-bgmi.downloader.*]
disallow_untyped_defs = false

[mypy-bgmi.website.mikan]
disallow_untyped_defs = false

[mypy-bgmi.website.bangumi_moe]
disallow_untyped_defs = false

[mypy-bgmi.website.share_dmhy]
disallow_untyped_defs = false
