jobs:
- job: 'Docs'
  pool:
    vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

  strategy:
    matrix:
      Python36:
        python.version: '3.6'
#      Python37:
#        python.version: '3.7'

  steps:
    - template: /.azure-pipelines/templates/steps/install-project.yaml
      parameters:
        python_version: $(python.version)

    - script: make html
      displayName: Build Docs
      workingDirectory: ./docs
