aliases:
  hash_deps: &hash_deps
    run:
      name: Hash Requirement files
      command: |
        echo $(find ./requirements -type f -exec md5sum {} \; | md5sum | cut -d' ' -f1) > .circleci/PIP_CACHE_KEY
        cat .circleci/PIP_CACHE_KEY
  restore_pip_cache: &restore_pip_cache
    restore_cache:
      keys:
        - pip-v1-{{ .Branch }}-{{ checksum ".circleci/PIP_CACHE_KEY" }}
        - pip-v1-{{ .Branch }}-
        - pip-v1-
  install_pip_deps: &install_pip_deps
    run:
      name: Install Dependencies
      command: |
        sudo pip install pip -U
        sudo pip install codecov -r requirements/dev.txt
  save_pip_cache: &save_pip_cache
    save_cache:
      key: pip-v1-{{ .Branch }}-{{ checksum ".circleci/PIP_CACHE_KEY" }}
      paths:
        - /home/circleci/.cache/pip
        - /home/circleci/.cache/pre-commit
  upload_codecov_report: &upload_codecov_report
    run:
      when: on_success
      name: Upload Coverage Report
      command: codecov

version: 2.1

workflows:
  version: 2
  main:
    jobs:
      - unittest
      - test_downloader
jobs:
  unittest:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout # check out the code in the project directory
      - *hash_deps
      - *restore_pip_cache
      - *install_pip_deps
      - *save_pip_cache

      - run:
          name: Code Style
          command: pre-commit run --all-files

      - run:
          name: Unittest
          command: coverage run -m pytest bgmi --ignore=bgmi/downloader

      - *upload_codecov_report

  test_downloader:
    docker:
      - image: circleci/python:3.6
      - image: linuxserver/deluge
        environment:
          PUID: "1001"
          PGID: "1000"
          TZ: "Asia/Shanghai"
          UMASK_SET: "022"

      - image: bgmidocker/aria2:latest
        environment:
          RPC_SECRET: aria2-rpc-secret

      - image: caseyfw/transmission
        environment:
          UID: '1000'
          USERNAME: "transmission-rpc-username"
          PASSWORD: "example-rpc-password"
    steps:
      - checkout # check out the code in the project directory
      - *hash_deps
      - *restore_pip_cache
      - *install_pip_deps
      - *save_pip_cache

      - run:
          name: Wait for Docker Ready
          command: |
            # wait for mysql start up
            for i in `seq 1 100`;
              do
                nc -z 127.0.0.1 8112 && nc -z 127.0.0.1 6800 && nc -z 127.0.0.1 9091 && echo Success && exit 0
                echo -n .
                sleep 0.1
              done
            echo Failed waiting for MySQL && exit 1

      - run:
          name: test downloader
          command: coverage run -m pytest bgmi/downloader
          environment:
            BGMI_TRANSMISSION_RPC_URL: http://transmission-rpc-username:example-rpc-password@127.0.0.1:9091/transmission/rpc
            BGMI_ARIA2_RPC_TOKEN: token:aria2-rpc-secret

      - *upload_codecov_report
