jobs:
  - job: "Binary"
    pool:
      vmImage: "$(os)"

    strategy:
      matrix:
        Windows:
          os: "windows-latest"
          name: windows
        Linux:
          os: "ubuntu-latest"
          name: linux
    #        MacOS:
    #          os: "macos-latest"

    steps:
      - template: /.ci/templates/install-project.yaml
        parameters:
          python_version: "3.7"

      - script: pyinstaller bgmi.spec

      - publish: "./dist/"
        artifact: "$(Agent.JobName)"

      - bash: mv dist/bgmi* dist/bgmi-$(name)

      # GitHub Release
      # Create, edit, or delete a GitHub release
      - task: GitHubRelease@0
        inputs:
          gitHubConnection: github release
          repositoryName: "$(Build.Repository.Name)"
          action: "edit" # Options: create, edit, delete
          target: "$(Build.SourceVersion)" # Required when action == Create || Action == Edit
          tagSource: "auto" # Required when action == Create# Options: auto, manual
          tagPattern: ".*" # Optional
          #tag: # Required when action == Edit || Action == Delete || TagSource == Manual
          #title: # Optional
          #releaseNotesSource: 'file' # Optional. Options: file, input
          #releaseNotesFile: # Optional
          #releaseNotes: # Optional
          assets: "./dist/*" # Optional
          assetUploadMode: "replace" # Optional. Options: delete, replace
