openapi: 3.0.0
info   :
  title  : BGmi HTTP API
  version: 1.0.1

  #description: This is a sample server for a pet store.
  #termsOfService: http://example.com/terms/

  contact:
    name: GitHub issues
    url : https://github.com/BGmi/BGmi/issues

  license:
    name: MIT
    url : https://github.com/BGmi/BGmi/blob/master/LICENSE


paths  :
  '/':
    get:
      responses:
        200:
          description: index page
          content    :
            application/json:
              schema:
                type      : object
                properties:
                  id      :
                    type       : integer
                    description: The user ID.
                  username:
                    type       : string
                    description: The user name.
