steps:
  - bash: |
      until curl -sSL https://raw.githubusercontent.com/codecov/codecov-bash/master/codecov -o codecov
      do
        echo "Try again"
      done

      until bash codecov
      do
        echo "Try again"
      done
    condition: always()
