parameters:
  python_version: '3.6'  # defaults for any parameters that aren't specified
  os: 'linux'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '${{ parameters.python_version }}'

  - template: ./cache-pip.yaml

  - bash: |
      python -m pip install toml==0.10.0
      python .ci/export_requirements.py --all
      pip install --no-deps -r requirements.txt
      curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      echo "##vso[task.prependpath]$HOME/.poetry/bin"
    displayName: Install Poetry

  - bash: |
      poetry config settings.virtualenvs.create false
      poetry install
    displayName: Install Packages
