parameters:
  python_version: '3.6'  # defaults for any parameters that aren't specified
  os: 'linux'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '${{ parameters.python_version }}'

  - bash: |
      echo "##vso[task.setvariable variable=PY]$(python -VV)"
    displayName: set env variables

  - task: Cache@2
    inputs:
      key: '"pip" | "3" | "$(Agent.OS)" | "$(PY)" | poetry.lock'
      restoreKeys: |
        "pip" | "3" | "$(Agent.OS)" | "$(PY)" | poetry.lock
        "pip" | "3" | "$(Agent.OS)" | "$(PY)"
      path: $(Build.Repository.LocalPath)/.venv
    displayName: Cache pip

  - bash: |
      curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      echo "##vso[task.prependpath]$HOME/.poetry/bin"
    displayName: Install Poetry

  - bash: |
      poetry config virtualenvs.in-project true
      poetry install -E docs
      if [[ "$(Agent.OS)" == 'Windows_NT' ]];then
        echo "##vso[task.prependpath]$PWD/.venv/Scripts"
      else
        echo "##vso[task.prependpath]$PWD/.venv/bin"
      fi
    displayName: Install Packages
