jobs:
- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016' # other options: 'macOS-10.13', 'vs2017-win2016'

  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
    - template: /.azure-pipelines/templates/steps/install-project.yaml
      parameters:
        python_version: $(python.version)

    - template: /.azure-pipelines/templates/steps/commands.yaml

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'junit/test_*.xml'
        testRunTitle: 'Publish test results for Python $(python.version)'
