ACTION_ADD = 'add'
ACTION_FETCH = 'fetch'
ACTION_FILTER = 'filter'
ACTION_DELETE = 'delete'
ACTION_UPDATE = 'update'
ACTION_CAL = 'cal'
ACTION_CONFIG = 'config'
ACTION_DOWNLOAD = 'download'
ACTION_LIST = 'list'
ACTION_MARK = 'mark'
ACTION_SEARCH = 'search'
ACTION_CONFIG_GEN = 'gen'
ACTION_LINK = 'link'
ACTION_UNLINK = 'unlink'
ACTION_COMPLETE = 'complete'  # bash completion
ACTIONS = (
    ACTION_ADD, ACTION_DELETE, ACTION_UPDATE, ACTION_CAL, ACTION_CONFIG, ACTION_FILTER,
    ACTION_FETCH, ACTION_DOWNLOAD, ACTION_LIST, ACTION_MARK, ACTION_SEARCH, ACTION_COMPLETE,
    ACTION_LINK, ACTION_UNLINK
)
ACTION_HISTORY = 'history'
