# specific branch build with batching
trigger:
  batch: true
  branches:
    include:
      - '*'
    exclude:
      - dependabot/*

stages:
- stage: Test
  jobs:
    - template: ./templates/jobs/base-unittest.yaml
    - template: ./templates/jobs/test-downloader.yaml
    - template: ./templates/jobs/test-controller.yaml
    - template: ./templates/jobs/test-sqlite.yaml
    - template: ./templates/jobs/test-mysql.yaml
- stage: Command_Test
  jobs:
    - template: /.azure-pipelines/templates/jobs/platform/windows.yaml
    - template: /.azure-pipelines/templates/jobs/platform/linux.yaml
    - template: /.azure-pipelines/templates/jobs/platform/macos.yaml
- stage: Build
  jobs:
    - template: ./templates/jobs/build-docker.yaml
    - template: ./templates/jobs/build-binary.yaml
    - template: ./templates/jobs/build-docs.yaml
