stages:
- stage: Test
  jobs:
    - template: ./templates/jobs/base-unittest.yaml
    - template: ./templates/jobs/test-downloader.yaml
    - template: ./templates/jobs/test-sqlite.yaml
    - template: ./templates/jobs/test-mysql.yaml
- stage: Build
  jobs:
    - template: ./templates/jobs/build-docker.yaml
    - template: ./templates/jobs/build-binary.yaml
    - template: ./templates/jobs/build-docs.yaml
