name: ci

on: [push, pull_request]

jobs:
  test-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
      - uses: Trim21/setup-poetry@dist/v1

      - run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}

      - run: |
          pip install twine
          twine check dist/*
