name: Tests
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  Linting:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64' # (x64 or x86)

      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-3.6-${{ hashFiles('poetry.lock') }}

      - name: Cache pre-commit
        uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pip-3.6-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install deps
        run: |
          python -m pip install toml==0.10.0
          python .ci/export_requirements.py --all
          pip install -r requirements.txt

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Mypy
        run: mypy bgmi
