name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
      - uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5
      - run: uv build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}

      # create GitHub release
      - name: Get Tag Name
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5

      - name: Install git-chglog
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest

      - name: Generate Changelog
        run: |
          git-chglog "$TAG" | node -p 'require("fs").readFileSync(0).toString().trim()
            .split("\n").slice(4).join("\n").trim()' | tee chglog.md

      - name: Upload Github Release
        run: gh release create "$TAG" -F chglog.md ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
